backend:
  name: github
  branch: master
  repo: csmith3621/clinger-pro

media_folder: static/img
public_folder: /img

collections:
- label: "Team"
  name: "team"
  folder: "src/team"
  create: true
  slug: "{{slug}}"
  fields:
  - { label: "Team Member", name: "title", widget: "string" }
  - { label: "Bio", name: "bio", widget: "markdown" }

- label: "Post"
  name: "posts"
  folder: "src/posts"
  create: true
  slug: "{{slug}}"
  fields: 
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Content", name: "body", widget: "markdown"}