backend:
  name: github
  branch: master
  repo: ModWrk/clinger-pro

media_folder: static/img
public_folder: /img

collections:
- label: "Team"
  name: "team"
  folder: "src/team"
  create: true
  slug: "{{slug}}"
  fields:
  - { label: "Team Member", name: "title", widget: "string" }